'https://www.planttext.com/?text=bLHDZzCm4BtxLmnxwYvR8N6C45gf4c8FN2ZYWb0qjIU9XJygsqasY_ZlZEsqsqKh19VM7h_np7lpdBkOCAJH6eY3RQN16CMhOy3U8YJoZv32I2BfP0YkzWC6Kc39-h100OFIs0UqLqBK_VxZfpqv1Jy5m1Qazq6raMohNUSRs9EzvyNJMGEx_7TJ8eUnwngGNANkvHW2kTI0Tga4vk0JjPt1le63zuQ3hqyLDp45xVfRYFgHsdIRawuBe0RAxMrURvw5OywTI2OVtXsMHE_hQRuU0g5Q6FxhWjrdajD_ilitSfrsEWwapjIsfVuBT7CBAzs_ChnanNT9qXDjAlPbadpdA5DjUkLOxforIaEpbbdf7PVsY3bwwh-4M0p6aSNZu0DL4Ygqqe-PwiuxzHL32HilVyGMPUAclhtzta2OS-ZYp11EJF7FGuK92yjoiFR4pJls1WJT3qdSmwoD0Ox0W1F11qCF-i0MnX1moGO-K00HFTo3pHc04MRY54kXfrK0T4hic1JNS98OYcwPETqHFuBamQ8RqPX5I9QGQwVXL61pD2Z9ydWPF7DcFrACro8_ZDoc49lhh59R7TJft5g4ADahgzDMgTOfPF8Ds37HGzbF62w5TqedxLrJbbCHcAVljO8PTMfPUsqsv_TG3jY8hgUduAvcrW2hAKuF-MQxhOsTlEyl0cT4zNaPWQ4kWNTWjCi3-yAgd0sHDQrOxJ2tp03i-q1zsRsHtXvzB6I0lqnfZC28G9rXAxF0c7zeOPa95B5T_SApOCXXAVBdnqpXjam-xrVJXoVbBrdKfaMTTcLH_Idk6CyVnTy0
@startuml shm_class
!pragma teoz true
title "Shared memory class diagram"

class SHMSend {
  - coord_sem_info: SemInfo
  - coord: Coord*
  - buff: char*
  - current: int
  - wrote_flag: bool
  + SHMSend(string, size_t, int)
  + size_t buff_size()
  + size_t send(vector<byte>)
  + bool ready()
}

class SHMRecv {
  - coord_sem_info: SemInfo
  - coord: Coord
  - buff: char*
  - current: int
  - finished: bool
  - read_flag: bool
  + SHMRecv(string)
  + size_t buff_size()
  + vector<byte> receive(size_t)
  + bool ready()
}

struct Coord {
  - buff_width: size_t
  - copy_path: int
  - copy_sem: semaphore
  - rdr_count: CondVar
  - locks_active[2]: rwlock
  - locks_leaving[2]: rwlock
  - data_size[2]: size_t
}

note right
I will not have Flexible array member 
so I might as well merge Coord and
Copy since I anyway need to manually
create the array (placement new I guess)
end note

() sem_coord_file as scrd

class CondVar {
  - lock: mutex
  - var: int
  - condition: condvar
  + void wait_until(int)
  + void change(int)
  + Condvar(int)
}


SHMSend *-- scrd
SHMRecv o-- scrd
SHMSend *-- Coord
note left on link
  The semaphore and Coordination
  aggregation/composition status 
  reflect that they are destroyed 
  by the sender, not the receiver
end note
SHMRecv o-- Coord

Coord *-- CondVar

@enduml